version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: .docker/app/Dockerfile
    working_dir: "/app"
    command: python main.py
    stdin_open: true
    tty: true
    ports:
      - "7000:7000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
  node:
    build:
      context: ./
      dockerfile: .docker/node/Dockerfile
    command: yarn start
    working_dir: "/app"
    volumes:
      - .:/app
    ports:
      - "7001:7001"
